"""
AskGovRAGBot Backend API Server
===============================

This module implements the core FastAPI REST API backend for the AskGovRAGBot application.
It acts as the primary gateway (controller) receiving request payloads from the front-end,
executing governed agent logic via the compiled LangGraph workflow state machine, recording
observability performance metrics using Prometheus, and offloading log writes to SQLite
asynchronously using FastAPI background tasks to maintain low client response latencies.

Architectural Context:
----------------------
1. Routing Layer: Translates REST requests to LangGraph inputs and maps execution outputs.
2. Background Logging: Database writes are processed via BackgroundTasks to bypass I/O blocks.
3. Metric Instrumentation: Scraped by Prometheus to monitor application usage and health.
4. CORS & Static Serves: Provides cross-origin access and serves the static HTML/CSS/JS interface.

Dependencies:
-------------
- fastapi: REST endpoints, route handlers, and dependency injection.
- uvicorn: ASGI web server runner.
- prometheus_client: Custom instrumented counters and latency histograms.
- pydantic: Input validation and response schema definition.
- sqlite3: SQLite database logging interface.
"""

import os
import time
from typing import List, Dict, Any, Optional
from pydantic import BaseModel, Field
from fastapi import FastAPI, HTTPException, BackgroundTasks, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import Response
from prometheus_client import Counter, Histogram, generate_latest, CONTENT_TYPE_LATEST

from app.config import settings
from app.database import init_db, log_interaction, log_feedback
from app.graph import compiled_graph

# Initialize persistent SQLite tables on application startup
init_db()

# Create and configure the FastAPI application instance
app = FastAPI(
    title="AskGovRAGBot API",
    description="Enterprise-grade governed policy Q&A assistant with RBAC filtering and PII masking.",
    version="1.0.0"
)

# Enable CORS (Cross-Origin Resource Sharing) middleware to allow browser calls from arbitrary origins
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# =============================================================================
# PROMETHEUS OBSERVABILITY METRICS
# =============================================================================

REQUESTS_TOTAL = Counter(
    "askgovragbot_api_requests_total",
    "Total count of incoming HTTP REST requests processed by the server endpoints.",
    labelnames=["role", "endpoint"]
)

LATENCY_HISTOGRAM = Histogram(
    "askgovragbot_request_duration_seconds",
    "Duration of request processing cycles measured in fractional seconds.",
    labelnames=["endpoint"]
)

PII_MASKED_COUNTER = Counter(
    "askgovragbot_pii_masked_total",
    "Total count of sensitive PII tokens identified and masked in query text structures.",
    labelnames=["role"]
)

HALLUCINATION_COUNTER = Counter(
    "askgovragbot_hallucinations_detected_total",
    "Total count of generated answers rejected by the LLM groundedness judge."
)

# =============================================================================
# DATA TRANSFER OBJECTS (Pydantic Request/Response Schemas)
# =============================================================================

class ChatRequest(BaseModel):
    """
    Data transfer object representing an incoming user chat query.
    
    Attributes:
        query (str): The raw text of the question submitted by the user.
        user_role (str): The enterprise role of the requester (Contractor, Employee, Manager, Admin).
        session_id (str): A unique conversation thread identifier used for persistent memory retrieval.
    """
    query: str = Field(..., description="The user question/query.")
    user_role: str = Field("Employee", description="User role: Contractor, Employee, Manager, Admin.")
    session_id: str = Field("default-session", description="Thread session ID for multi-turn history.")

class ChatResponse(BaseModel):
    """
    Data transfer object containing the processed response returned to the client.
    
    Attributes:
        session_id (str): The conversation thread ID representing the session state.
        run_id (str): A unique identifier assigned to this specific request execution run.
        response (str): The final, governed, de-masked policy answer generated by the system.
        nodes_visited (List[str]): The execution path showing which nodes were triggered in the state graph.
        is_grounded (bool): Flag indicating if the response passed the output groundedness check.
        groundedness_score (float): The quantitative evaluation score assigned by the LLM-as-a-judge.
        pii_masked_count (int): The number of sensitive data entities anonymized during the call.
    """
    session_id: str
    run_id: str
    response: str
    nodes_visited: List[str]
    is_grounded: bool
    groundedness_score: float
    pii_masked_count: int

class FeedbackRequest(BaseModel):
    """
    Data transfer object submitting human feedback evaluation ratings.
    
    Attributes:
        session_id (str): The conversation session ID associated with the logged run.
        run_id (str): The unique execution run identifier.
        rating (int): Score rating: 1 indicates positive feedback (thumbs-up), 0 indicates negative (thumbs-down).
        comment (str, optional): A text field detailing qualitative comments from the user.
    """
    session_id: str
    run_id: str
    rating: int = Field(..., description="1 for thumbs-up, 0 for thumbs-down.")
    comment: Optional[str] = Field(None, description="Optional text comment from user.")

# =============================================================================
# API REST CONTROLLERS (Endpoints)
# =============================================================================

@app.post("/api/chat", response_model=ChatResponse)
async def chat_endpoint(request: ChatRequest, background_tasks: BackgroundTasks) -> ChatResponse:
    """
    Accepts user questions, runs the LangGraph RAG pipeline, and logs the query metrics.
    
    This controller receives the request, validates the input role parameters, starts
    a high-resolution latency timer, and executes the compiled LangGraph workflow state 
    machine. Visited execution paths and PII metrics are calculated and logged. 
    Write-backs to the SQLite audit database are offloaded to background worker threads
    to minimize user waiting times.
    
    Args:
        request (ChatRequest): The chat request payload containing query, role, and session.
        background_tasks (BackgroundTasks): FastAPI manager to queue non-blocking async tasks.
        
    Returns:
        ChatResponse: Structured output including the generated answer, metadata, and traces.
        
    Raises:
        HTTPException: 400 Bad Request if the user role is invalid.
        HTTPException: 500 Internal Server Error if graph processing fails.
    """
    start_time = time.time()
    
    role = request.user_role.lower()
    if role not in ["contractor", "employee", "manager", "admin"]:
        raise HTTPException(status_code=400, detail="Invalid user role specified.")
        
    # Increment counter for request tracking
    REQUESTS_TOTAL.labels(role=request.user_role, endpoint="/api/chat").inc()
    
    try:
        # Construct execution config linking the state graph to standard session memory
        config = {"configurable": {"thread_id": request.session_id}}
        
        # Invoke the compiled state graph workflow
        result = compiled_graph.invoke({
            "query": request.query,
            "user_role": request.user_role,
            "nodes_visited": []
        }, config=config)
        
        # Calculate processing duration
        elapsed_time = time.time() - start_time
        LATENCY_HISTOGRAM.labels(endpoint="/api/chat").observe(elapsed_time)
        
        # Retrieve computed variables from the final graph state
        final_answer = result.get("final_answer", "")
        pii_map = result.get("pii_mapping", {})
        nodes_visited = result.get("nodes_visited", [])
        is_grounded = result.get("is_grounded", True)
        groundedness_score = result.get("groundedness_score", 1.0)
        
        # Increment PII masking counts if sensitive objects were found
        pii_count = len(pii_map)
        if pii_count > 0:
            PII_MASKED_COUNTER.labels(role=request.user_role).inc(pii_count)
            
        # Track hallucinated outcomes rejected by output guardrails
        if not is_grounded:
            HALLUCINATION_COUNTER.inc()
            
        # Create a unique run tracker ID using timestamps
        run_id = f"run_{int(start_time * 1000)}"
        
        # Format the retrieved documents for structured SQLite logs
        logged_docs = []
        for d in result.get("retrieved_docs", []):
            logged_docs.append({
                "page_content": d.page_content,
                "metadata": d.metadata
            })
            
        # Queue non-blocking write tasks to the SQL ledger database
        background_tasks.add_task(
            log_interaction,
            session_id=request.session_id,
            run_id=run_id,
            raw_query=request.query,
            masked_query=result.get("masked_query", ""),
            response=final_answer,
            user_role=request.user_role,
            retrieved_docs=logged_docs,
            nodes_visited=nodes_visited
        )
        
        return ChatResponse(
            session_id=request.session_id,
            run_id=run_id,
            response=final_answer,
            nodes_visited=nodes_visited,
            is_grounded=is_grounded,
            groundedness_score=groundedness_score,
            pii_masked_count=pii_count
        )
        
    except Exception as e:
        print(f"[CRITICAL] Error in chat_endpoint execution: {e}")
        raise HTTPException(status_code=500, detail=f"StateGraph execution failed: {e}")

@app.post("/api/feedback")
async def feedback_endpoint(request: FeedbackRequest) -> dict:
    """
    Submits user satisfaction rating scores and textual comments to the SQLite ledger database.
    
    This endpoint records direct human evaluations, logging ratings (1 for positive, 
    0 for negative) and optional text comments. These entries form our RLHF/fine-tuning 
    feedback loops and allow offline extraction of custom training datasets.
    
    Args:
        request (FeedbackRequest): Contains thread session ID, run ID, score, and comment.
        
    Returns:
        dict: Standard JSON confirmation block: {"status": "success", "message": "..."}
        
    Raises:
        HTTPException: 500 Internal Server Error if the SQL write-back fails.
    """
    REQUESTS_TOTAL.labels(role="anonymous", endpoint="/api/feedback").inc()
    
    try:
        log_feedback(
            session_id=request.session_id,
            run_id=request.run_id,
            rating=request.rating,
            comment=request.comment
        )
        return {"status": "success", "message": "Feedback logged successfully."}
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Feedback database writer failed: {e}")

@app.get("/metrics")
def metrics_endpoint() -> Response:
    """
    Exposes raw Prometheus metrics for collection and scraping by metrics collectors.
    
    Provides standard text outputs formatting the internal counts, hits, and latencies
    of our application endpoints using the Prometheus line format.
    
    Returns:
        Response: Structured metrics stream with standard content-type header settings.
    """
    return Response(generate_latest(), media_type=CONTENT_TYPE_LATEST)

# The backend is intentionally API-first and does not serve the frontend by default.
# This enables clean separation of the UI from the API service in production.
if os.getenv("SERVE_FRONTEND", "false").lower() == "true":
    from fastapi.staticfiles import StaticFiles
    frontend_dir = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "frontend")
    if os.path.exists(frontend_dir):
        app.mount("/", StaticFiles(directory=frontend_dir, html=True), name="frontend")
    else:
        print("[WARNING] Static frontend directory not found. Serving REST endpoints only.")
